#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
KITTY_DIR="$XDG_CONFIG_HOME/kitty"

common_deps=(
  kitty
)

brew_deps=(
  font-jetbrains-mono
)

apt_deps=(
  fonts-jetbrains-mono
)

link() {
  find "$KITTY_DIR" -maxdepth 1 -type l -delete
  mklink config "$KITTY_DIR"
}

install() {
  case $(_os) in
    macos)
      # Enable Cask of fonts
      brew install ${common_deps[@]} ${brew_deps[@]}
      ;;
    debian)
      sudo apt update
      if is_backports_configured; then
          sudo apt install -y -t bookworm-backports ${common_deps[@]} ${apt_deps[@]}
      else
          sudo apt install -y ${apt_deps[@]}
      fi
      ;;
  esac
}

update() {
  link
}

clean() {
  rm -rfv "$KITTY_DIR"
}

init "$@"
