#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
KITTY_DIR="$XDG_CONFIG_HOME/kitty"

common_deps=(
  kitty
)

brew_deps=(
  font-jetbrains-mono
)

link() {
  find "$KITTY_DIR" -maxdepth 1 -type l -delete
  mklink config "$KITTY_DIR"
}

install() {
  case $(_os) in
    macos)
      # Enable Cask of fonts
      brew install ${common_deps[@]} ${brew_deps[@]}
      ;;
    debian)
      sudo apt update
      sudo apt install -y ${common_deps[@]}

      # Install font manually
      curl -fsSL https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/install_manual.sh | bash
      ;;
  esac
}

update() {
  link
}

clean() {
  rm -rfv "$KITTY_DIR"
}

init "$@"
