#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

# Dependencies

common_deps=(
  tmux
)

brew_deps=(
 reattach-to-user-namespace
)

link() {
  mklink *.conf     $TMUX_HOME/
}

install() {
  case $(_os) in
    macos)
      brew install ${common_deps[@]} ${brew_deps[@]}
      ;;
    debian)
      sudo apt update && sudo apt install -y ${common_deps[@]}
      ;;
  esac

  [[ -n $TMUXIFIER ]] && _ensure_repo jimeh/tmuxifier $TMUXIFIER

  local tpm=$TMUX_PLUGINS_HOME/tpm
  _ensure_repo tmux-plugins/tpm $tpm
  $tpm/bin/install_plugins
}

update() {
  local tpm=$TMUX_PLUGINS_HOME/tpm
  if [[ -d $tpm ]]; then
    $tpm/bin/install_plugins
    $tpm/bin/update_plugins all
    $tpm/bin/clean_plugins all
  fi

  if [[ -d $TMUXIFIER ]]; then
    cd $TMUXIFIER && git pull --rebase
  fi
}

clean() {
  rm -rfv "$TMUX_HOME" "$TMUX_PLUGINS_HOME" "$TMUXIFIER"
}

init "$@"
