#!/usr/bin/env zsh

source ${0:A:h}/../../deploy

# link() {}

# install() {}

update() {
  case $(_os) in
    debian)
      sudo apt update && sudo apt upgrade -y
      ;;
  esac
}

# clean() {}

init "$@"
