#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

SURFINGKEYS_CONF_PATH="$XDG_CONFIG_HOME/surfingkeys.js"

# install() {}

# update() {}

link() {
  mklink surfingkeys.js $XDG_CONFIG_HOME

  echo
  echo-note "To complete the setup you will need to do the following in Chrome:"
  echo "- Go to the Chrome's extension settings, Look for Surfingkeys, Click the 'Details' button and enable 'Allow access to file URLs'"
  echo "- Open the Surfingkeys options and check the option 'Advanced mode'"
  echo "- Paste the following path in 'Load settings from':"
  echo -n "$(tput bold)"
  echo "  $SURFINGKEYS_CONF_PATH"
  echo -n "$(tput sgr0)"
  echo "- Click Save and refresh your tabs to apply changes"
  echo
}

clean() {
  rm -fv "$SURFINGKEYS_CONF_PATH"
}

init "$@"
