#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.bash

install() {
  case $(_os) in
    macos)
      brew install sbdchd/skim/skim
      ;;
    debian)
      git clone --depth 1 git@github.com:lotabout/skim.git "$SKIM_DIR"
      $SKIM_DIR/install
      ;;
  esac
}

update() {
  if [[ $(_os) == debian ]]; then
    if [[ -n $SKIM_DIR ]]; then
      cd $SKIM_DIR && git pull
    else
      git clone --depth 1 git@github.com:lotabout/skim.git "$SKIM_DIR"
      $SKIM_DIR/install
    fi
  fi
}

# link() {}

clean() {
  [[ $(_os) == debian ]] && rm -rfv "$SKIM_DIR"
}

init "$@"
