#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

brew_deps=(
  bpytop
  hacker1024/hacker1024/coretemp
  gtypist
  highlight
  mvtools
  p7zip
  rsync
  tree
  rar
  wget
  adobe-acrobat-reader
  alfred
  android-file-transfer
  appcleaner
  bruno
  calibre
  chatgpt
  deepl
  ffmpeg
  ffms2
  grandperspective
  keka
  keycastr
  orbstack
  omnidisksweeper
  prettyping
  provisionql
  qlcolorcode
  qlmarkdown
  qlprettypatch
  qlstephen
  qlvideo
  quicklook-json
  quicklookase
  skim
  slack
  spotify
  suspicious-package
  visual-studio-code
  vlc
  webpquicklook
  yt-dlp
)

cask_deps=(
  handbrake
  obsidian
  syncthing
)

# link() {}

install() {
  case $(_os) in
    macos)
      brew install ${brew_deps[@]}
      brew install --cask ${cask_deps[@]}
      brew tap cjbassi/gotop
      brew install gotop
      brew tap teamookla/speedtest
      brew install speedtest
      ;;
  esac
}

update() {
  install
}

# clean() {}

init "$@"
