#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

brew_deps=(
  bpytop
  hacker1024/hacker1024/coretemp
  gtypist
  highlight
  mvtools
  neofetch
  p7zip
  rsync
  tree
  rar
  wget
  adobe-acrobat-reader
  alfred
  android-file-transfer
  appcleaner
  calibre
  ffmpeg
  ffms2
  grandperspective
  handbrake
  keka
  keycastr
  syncthing
  omnidisksweeper
  prettyping
  provisionql
  qlcolorcode
  qlimagesize
  qlmarkdown
  qlprettypatch
  qlstephen
  qlvideo
  quicklook-json
  quicklook-pat
  quicklookapk
  quicklookase
  slack
  spotify
  suspicious-package
  visual-studio-code
  vlc
  webpquicklook
  deepl
  bruno
  skim
)

# link() {}

install() {
  case $(_os) in
    macos)
      brew install ${brew_deps[@]}
      brew tap cjbassi/gotop
      brew install gotop
      brew tap teamookla/speedtest
      brew install speedtest
      ;;
  esac
}

# update() {}

# clean() {}

init "$@"
