#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

brew_deps=(
  lua
  luarocks
  lua-language-server
)

# link() {}

install() {
  case $(_os) in
    macos)
      brew install ${brew_deps[@]}
      ;;
  esac

  _ensure_repo cehoffman/luaenv     $LUAENV_ROOT
  _ensure_repo cehoffman/lua-build  $LUAENV_ROOT/plugins/lua-build
  _ensure_repo xpol/luaenv-luarocks $LUAENV_ROOT/plugins/luaenv-luarocks
}

update() {
  if [[ -n $LUAENV_ROOT ]]; then
    cd $LUAENV_ROOT && git pull
    for ver in $LUAENV_ROOT/plugins/*(/); do
      cd $ver && git pull
    done
  fi

  luaenv install 5.3.6
  luaenv global 5.3.6
  luaenv luarocks
  luarocks install luacheck
  luarocks install --server=http://luarocks.org/dev lua-lsp
}

clean() {
  rm -rfv "$LUAENV_ROOT" "$XDG_CACHE_HOME/zsh/luaenv"
}

init "$@"
