#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

brew_deps=(
  lua
  luarocks
  lua-language-server
)

apt_deps=(
  lua5.4
  luarocks
)

luarocks_deps=(
  luacheck
)

# link() {}

install() {
  case $(_os) in
    macos)
      brew install ${brew_deps[@]}
      ;;
    debian)
      sudo apt update
      sudo apt install -y ${apt_deps[@]}
      ;;
  esac

  luarocks install ${luarocks_deps[@]}
  echo-note "Set your global Lua version via: mise use --global lua@latest"
}

update() {
  case $(_os) in
    macos)
      brew upgrade ${brew_deps[@]}
      ;;
    debian)
      sudo apt install -y ${apt_deps[@]}
      ;;
  esac

  luarocks install ${luarocks_deps[@]}
}

clean() {
  rm -rfv "$XDG_CACHE_HOME/zsh/luaenv"
}

init "$@"
