#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

pip_deps=(
  black
  nose
  pyflakes
  isort
  pipenv
  pytest
  setuptools
  nose
  "python-lsp-server[all]"
)

link() {
  mklink config/flake8 $XDG_CONFIG_HOME
}

apt_deps=(
  build-essential
  libssl-dev
  zlib1g-dev
  libbz2-dev
  libreadline-dev
  libsqlite3-dev
  libncursesw5-dev
  xz-utils
  tk-dev
  libxml2-dev
  libxmlsec1-dev
  libffi-dev
  liblzma-dev
)

install() {
  # Install Python build dependencies
  case $(_os) in
    debian)
      sudo apt update
      sudo apt install -y ${apt_deps[@]}
      ;;
  esac

  # Install pyenv
  echo-note "Install pyenv"
  curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
  eval "$(pyenv init -)"

  echo-note "Install latest Python version as global"
  local python_latest="3"
  pyenv install $python_latest
  pyenv global $python_latest

  echo-note "Setup development tools"
  pip3 install ${pip_deps[@]}
  # Install pyright using node, not pip, which annoyingly insists on adding nodeenv just for this package! (゜-゜)
  topic-enabled-p dev/node || _dot dev/node
  npm install -g pyright
  nodenv rehash
}

update() {
  pyenv update
  npm install -g --force pyright # install or update
  nodenv rehash
}

clean() {
  rm -rfv "$XDG_CONFIG_HOME/flake8" "$PYENV_ROOT" "$XDG_CACHE_HOME/zsh/pyenv"
}

init "$@"
