#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

pip_deps=(
  ruff          # linter + formatter: replaces pyflakes, black, isort
  pytest
  setuptools
  "python-lsp-server[all]"
)

# Build dependencies required by mise/pyenv to compile Python from source
apt_build_deps=(
  build-essential
  libssl-dev
  zlib1g-dev
  libbz2-dev
  libreadline-dev
  libsqlite3-dev
  libncursesw5-dev
  xz-utils
  tk-dev
  libxml2-dev
  libxmlsec1-dev
  libffi-dev
  liblzma-dev
)

link() {
  mklink config/flake8 $XDG_CONFIG_HOME
}

install() {
  # Install Python build dependencies so mise can compile Python from source
  case $(_os) in
    debian)
      sudo apt update
      sudo apt install -y ${apt_build_deps[@]}
      ;;
  esac

  echo-note "Set your global Python version via: mise use --global python@latest"
  echo-note "Setup development tools"
  pip3 install ${pip_deps[@]}
}

update() {
  pip3 install --upgrade ${pip_deps[@]}
}

clean() {
  rm -rfv "$XDG_CONFIG_HOME/flake8" "$XDG_CACHE_HOME/zsh/pyenv"
}

init "$@"
