#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  case $(_os) in
    macos)  brew install bash bash-completion coreutils ;;
    debian) sudo apt-get install -y bash ;;
  esac

  exec bash
}

# update() { }

link() {
  mklink .bash* ~/
}

clean() {
  rm -fv ~/.bash{rc,_profile}
}

init "$@"
