#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

# Dependencies

common_deps=(
  the_silver_searcher
  ripgrep
  sqlite
  zstd
  fd
  editorconfig
)

brew_deps=(
  pandoc
  markdown
  coreutils
  gnu-tar
  llvm
  cmake
  glslang
  pyenv
  jq
  black
  aspell
  pngpaste # org-download
  trash
  marked
  shellcheck
  graphviz # graph visualizator - org-roam dep
)

cask_fonts_deps=(
  font-hack
  font-hack-nerd-font
  font-noto-sans
  font-noto-serif
)

install() {
  case $(_os) in
    macos)
      brew install ${common_deps[@]} ${brew_deps[@]}
      # Enable Cask of fonts
      brew tap homebrew/cask-fonts
      brew install ${cask_fonts_deps[@]}
      brew tap railwaycat/emacsmacport
      brew install emacs-mac --with-modules
      ;;
  esac

  # Clone and setup doom-emacs
  _ensure_repo eduarbo/doom-emacs $XDG_CONFIG_HOME/emacs develop

  $XDG_CONFIG_HOME/emacs/bin/doom -y install
}

update() {
  doom upgrade
}

link() {
  mklink doom $XDG_CONFIG_HOME
  # TODO: Check if editorconfig supports XDG Base Directory
  mklink editorconfig ~/.editorconfig
}

clean() {
  rm -rfv "$XDG_CONFIG_HOME/doom" "~/.emacs.d"
  rm -fv ~/.editorconfig
}

init "$@"
