#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

# Dependencies

common_deps=(
  the_silver_searcher
  ripgrep
  sqlite
  zstd
  fd
  editorconfig
)

brew_deps=(
  pandoc
  markdown
  coreutils
  gnu-tar
  node
  llvm
  cmake
  glslang
  pyenv
  jq
  black
  hunspell
  pngpaste # org-download
  trash
  marked
  shellcheck
)

node_deps=(
  eslint_d
  prettier
  typescript
  typescript-language-server
  vscode-css-languageserver-bin
  vscode-html-languageserver-bin
  stylelint
  bash-language-server
)

cask_fonts_deps=(
  font-hack
  font-hack-nerd-font
  font-noto-sans
)

install() {
  case $(_os) in
    macos)
      brew install ${common_deps[@]} ${brew_deps[@]}
      # Enable Cask of fonts
      brew tap homebrew/cask-fonts
      brew install ${cask_fonts_deps[@]}
      brew tap d12frosted/emacs-plus
      brew install emacs-plus --with-mailutils
      ;;
  esac
  # TODO allow installation of global node packages
  npm install -g ${node_deps[@]}

  # Clone and setup doom-emacs
  _ensure_repo eduarbo/doom-emacs ~/.emacs.d develop

  ~/.emacs.d/bin/doom -y install
}

update() {
  doom upgrade
}

link() {
  mklink doom $XDG_CONFIG_HOME
  mklink dictionaries/* "$HOME/Library/Spelling"
  # TODO: Check if editorconfig supports XDG Base Directory
  mklink editorconfig ~/.editorconfig
}

clean() {
  rm -rfv "$XDG_CONFIG_HOME/doom" "~/.emacs.d"
  rm -fv ~/.editorconfig
}

init "$@"
