#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
FZF_DIR="$XDG_CONFIG_HOME/fzf"

# Dependencies

install() {
  case $(_os) in
    macos)
      brew install fzf
      ;;
    debian)
      git clone --depth 1 https://github.com/junegunn/fzf.git /tmp/fzf
      /tmp/fzf/install
      ;;
  esac
}

# update() {
# }

# link() {
# }

clean() {
  rm -rfv "$FZF_DIR"
}

init "$@"
