#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
GIT_DIR="$XDG_CONFIG_HOME/git"

# Dependencies

common_deps=(
  git
)

zplugin_deps=(
  zdharma/zsh-diff-so-fancy
  tj/git-extras
)

install() {
  case $(_os) in
    macos)
      brew install ${common_deps[@]}
      ;;
    debian)
      sudo apt update && sudo apt install -y ${common_deps[@]}
      ;;
  esac

  # Kill zcompdump to take new compdefs
  rm -f "${ZINIT[ZCOMPDUMP_PATH]}"
  rm -f "${ZINIT[ZCOMPDUMP_PATH]}.zwc"
}

update() {
  if [[ -e ${ZINIT[BIN_DIR]}/zplugin.zsh ]]; then
    source ${ZINIT[BIN_DIR]}/zplugin.zsh

    for plugin in "${zplugin_deps[@]}" ; do
      zplugin update $plugin
      zplugin compile $plugin
    done
  fi
}

link() {
  mklink {config,ignore,message} "$GIT_DIR/"
}

clean() {
  rm -rfv $GIT_DIR

  if [[ -e ${ZINIT[BIN_DIR]}/zplugin.zsh ]]; then
    source ${ZINIT[BIN_DIR]}/zplugin.zsh

    for plugin in "${zplugin_deps[@]}" ; do
      zplugin delete $plugin
    done
  fi
}

init "$@"
