#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

deps=(dev/mise)

brew_deps=(
  go
  gotests
)

golang_deps=(
  github.com/jessfraz/dockfmt@latest
  golang.org/x/tools/gopls@latest # code completion
  github.com/fatih/gomodifytags@latest
  github.com/x-motemen/gore/cmd/gore@latest
)

# link() {}

install() {
  case $(_os) in
    macos)
      brew install ${brew_deps[@]}
      ;;
    *)
      if ! _is_callable go; then
        if _is_callable mise; then
          echo-info "Installing Go via mise..."
          mise use --global go@latest
          eval "$(mise activate zsh)"
        else
          echo-fail "Neither go nor mise found. Install dev/mise first."
          return 1
        fi
      fi
      ;;
  esac

  echo-note "Installing golang dependencies"
  for dep in "${golang_deps[@]}"; do
    go install "$dep"
  done
}

update() {
  install
}

# clean() {
# }

init "$@"
