#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
KITTY_DIR="$XDG_CONFIG_HOME/kitty"

# only for macOS
[[ $(_os) != macos ]] && exit

brew_deps=(
  kitty
  font-hack
  font-jetbrains-mono
)

link() {
  find "$KITTY_DIR" -maxdepth 1 -type l -delete
  mklink config "$KITTY_DIR"
}

install() {
  # Enable Cask of fonts
  brew tap homebrew/cask-fonts

  brew install ${brew_deps[@]}
}

update() {
  link
}

clean() {
  rm -rfv "$KITTY_DIR"
}

init "$@"
