#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
KITTY_DIR="$XDG_CONFIG_HOME/kitty"

# only for macOS
[[ $(_os) != macos ]] && exit

install() {
  brew install kitty
  # Enable Cask of fonts
  brew tap homebrew/cask-fonts
  brew install font-hack
}

update() {
  link
}

link() {
  find "$KITTY_DIR" -maxdepth 1 -type l -delete
  mklink config/* "$KITTY_DIR"
}

clean() {
  rm -rfv "$KITTY_DIR"
}

init "$@"
