#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

# npm packages to install globally
global_npm_packages=(
  pyright # Python language server (avoids adding nodeenv just for this)
)

link() {
  mklink prettierrc.js "$HOME/.prettierrc.js"
}

install() {
  if ! _is_callable node; then
    echo-fail "Node.js not found. Install it first: dot dev/mise && mise use --global node@lts"
    return 1
  fi

  case $(_os) in
    macos)
      brew install pnpm
      ;;
    debian)
      npm install -g pnpm
      ;;
  esac

  npm install -g ${global_npm_packages[@]}
}

update() {
  npm update -g ${global_npm_packages[@]}
  case $(_os) in
    macos)
      brew upgrade pnpm
      ;;
    debian)
      npm install -g pnpm
      ;;
  esac
}

clean() {
  rm -rfv "$HOME/.prettierrc.js"
}

init "$@"
