#!/usr/bin/env zsh

source ${0:A:h}/../../deploy

os=(macos)

# link() {}

install() {
  ./bin/macosdefaults
}

update() {
  # Apply new macOS defaults
  ./bin/macosdefaults
}

# clean() {}

init "$@"
