#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

NVIM_CONFIG_DIR="$XDG_CONFIG_HOME/nvim"
NVIM_DATA_DIR="$XDG_DATA_HOME/nvim"
NVIM_CACHE_DIR="$XDG_CACHE_HOME/nvim"
PLUG_PATH="$NVIM_DATA_DIR/site/autoload/plug.vim"

common_deps=(
  neovim
  shfmt
)

link() {
  mklink config $NVIM_CONFIG_DIR
}

install() {
  case $(_os) in
    macos)
      brew install ${common_deps[@]}
      ;;
    debian)
      sudo apt update
      if is_backports_configured; then
        sudo apt install -y -t bookworm-backports ${common_deps[@]}
      else
        sudo apt install -y ${common_deps[@]}
      fi
      topic-enabled-p editor/coding-style || _dot editor/coding-style
      ;;
  esac

  if [ ! -f "$PLUG_PATH" ]; then
    echo-note "Downloading vim-plug..."
    curl -fLo "$PLUG_PATH" --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim || {
      echo-fail "Failed to download vim-plug"
      exit 1
    }
  fi

  if [ -f "$PLUG_PATH" ]; then
    echo-note "Installing plugins..."
    nvim --headless +PlugInstall +qall
  fi
}

update() {
  nvim --headless +PlugUpdate +qall
}

clean() {
  rm -rfv "$NVIM_CONFIG_DIR" "$NVIM_DATA_DIR" "$NVIM_CACHE_DIR"
}

init "$@"
