#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

NVIM_CONFIG_DIR="$XDG_CONFIG_HOME/nvim"
NVIM_DATA_DIR="$XDG_DATA_HOME/nvim"
NVIM_CACHE_DIR="$XDG_CACHE_HOME/nvim"
PLUGDIR="$NVIM_DATA_DIR/site/autoload"

brew_deps=(
  neovim
  shfmt
)

link() {
  mklink config $NVIM_CONFIG_DIR
}

install() {
  case $(_os) in
    macos)  brew install ${brew_deps[@]} ;;
  esac

  [ -f "$PLUGDIR" ] || curl -fLo $PLUGDIR --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  nvim --headless +PlugInstall +qall
}

update() {
  nvim --headless +PlugUpdate +qall
}

clean() {
  rm -rfv "$NVIM_CONFIG_DIR" "$NVIM_DATA_DIR" "$NVIM_CACHE_DIR"
}

init "$@"
