#!/usr/bin/env zsh

source ${0:A:h}/../../deploy

# install() {}

update() {
  sudo systemctl daemon-reload
}

link() {
  sudo systemctl link $DOTFILES/linux/systemd/*.{service,timer}
}

# clean() {}

init "$@"
